vcl {
  rx-fifo-size 524288
  tx-fifo-size 524288
  segment-size 1073741824
  add-segment-size 536870912
  event-queue-size 8192
  app-scope-global
  app-scope-local
  use-mq-eventfd
  app-socket-api /run/vpp/app_ns_sockets/default
}
